"""create_initial_catalog_tables

Revision ID: be26c8adf878
Revises: 
Create Date: 2026-09-23 16:19:09.098460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be26c8adf878'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('performance_cores', sa.Integer(), nullable=True),
    sa.Column('efficiency_cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('base_clock_ghz', sa.Numeric(), nullable=True),
    sa.Column('boost_clock_ghz', sa.Numeric(), nullable=True),
    sa.Column('tdp_w', sa.Numeric(), nullable=True),
    sa.Column('benchmark_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('display',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('size_inches', sa.Numeric(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.String(), nullable=True),
    sa.Column('refresh_rate_hz', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('brightness_nits', sa.Integer(), nullable=True),
    sa.Column('color_gamut', sa.String(), nullable=True),
    sa.Column('srgb_coverage', sa.Numeric(), nullable=True),
    sa.Column('dci_p3_coverage', sa.Numeric(), nullable=True),
    sa.Column('response_time_ms', sa.Numeric(), nullable=True),
    sa.Column('touchscreen', sa.Boolean(), nullable=True),
    sa.Column('oled', sa.Boolean(), nullable=False),
    sa.Column('hdr', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('vram_gb', sa.Numeric(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=True),
    sa.Column('tdp_w', sa.Numeric(), nullable=True),
    sa.Column('integrated', sa.Boolean(), nullable=False),
    sa.Column('benchmark_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_module',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_device',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_family',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_laptop_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_family_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_model', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['laptop_family_id'], ['laptop_family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_model_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_part_number', sa.String(), nullable=True),
    sa.Column('identity_hash', sa.String(), nullable=False),
    sa.Column('cpu_id', sa.UUID(), nullable=False),
    sa.Column('gpu_id', sa.UUID(), nullable=True),
    sa.Column('display_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu.id'], ),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu.id'], ),
    sa.ForeignKeyConstraint(['laptop_model_id'], ['laptop_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_hash')
    )
    op.create_table('battery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('capacity_wh', sa.Numeric(), nullable=True),
    sa.Column('cells', sa.Integer(), nullable=True),
    sa.Column('measured_runtime_h', sa.Numeric(), nullable=True),
    sa.Column('runtime_source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.ForeignKeyConstraint(['runtime_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('speaker_quality', sa.String(), nullable=True),
    sa.Column('speaker_loudness_db', sa.Numeric(), nullable=True),
    sa.Column('microphone_quality', sa.String(), nullable=True),
    sa.Column('headphone_output_quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_build',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('chassis_material', sa.String(), nullable=True),
    sa.Column('hinge_material', sa.String(), nullable=True),
    sa.Column('military_standard', sa.String(), nullable=True),
    sa.Column('durability_rating', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_configuration_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_configuration_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_configuration_id'], ['laptop_configuration.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_connectivity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('wifi_standard', sa.String(), nullable=True),
    sa.Column('bluetooth_version', sa.String(), nullable=True),
    sa.Column('ethernet', sa.Boolean(), nullable=True),
    sa.Column('ethernet_speed', sa.String(), nullable=True),
    sa.Column('has_hdmi', sa.Boolean(), nullable=True),
    sa.Column('has_displayport', sa.Boolean(), nullable=True),
    sa.Column('has_sd_card_reader', sa.Boolean(), nullable=True),
    sa.Column('has_headphone_jack', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_measurement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('length_mm', sa.Numeric(), nullable=True),
    sa.Column('width_mm', sa.Numeric(), nullable=True),
    sa.Column('height_mm', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('memory_module_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_soldered', sa.Boolean(), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=True),
    sa.Column('max_supported_gb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.ForeignKeyConstraint(['memory_module_id'], ['memory_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_port',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('port_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('supports_power_delivery', sa.Boolean(), nullable=True),
    sa.Column('supports_display_output', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('storage_device_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.ForeignKeyConstraint(['storage_device_id'], ['storage_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_storage_slot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('slot_type', sa.String(), nullable=False),
    sa.Column('interface', sa.String(), nullable=False),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.Column('supports_upgrade', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_thermals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('cpu_load_temp_c', sa.Numeric(), nullable=True),
    sa.Column('gpu_load_temp_c', sa.Numeric(), nullable=True),
    sa.Column('surface_temp_c', sa.Numeric(), nullable=True),
    sa.Column('fan_noise_db', sa.Numeric(), nullable=True),
    sa.Column('idle_noise_db', sa.Numeric(), nullable=True),
    sa.Column('sustained_performance', sa.Numeric(), nullable=True),
    sa.Column('throttling_observed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_webcam',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('megapixels', sa.Numeric(), nullable=True),
    sa.Column('has_ir', sa.Boolean(), nullable=True),
    sa.Column('has_privacy_shutter', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specification_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laptop_configuration_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_identifier', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['laptop_configuration_id'], ['laptop_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification_evidence')
    op.drop_table('laptop_webcam')
    op.drop_table('laptop_thermals')
    op.drop_table('laptop_storage_slot')
    op.drop_table('laptop_storage')
    op.drop_table('laptop_port')
    op.drop_table('laptop_memory')
    op.drop_table('laptop_measurement')
    op.drop_table('laptop_connectivity')
    op.drop_table('laptop_configuration_alias')
    op.drop_table('laptop_build')
    op.drop_table('laptop_audio')
    op.drop_table('battery')
    op.drop_table('laptop_configuration')
    op.drop_table('laptop_model')
    op.drop_table('raw_laptop_record')
    op.drop_table('laptop_family')
    op.drop_table('usage_category')
    op.drop_table('storage_device')
    op.drop_table('memory_module')
    op.drop_table('gpu')
    op.drop_table('display')
    op.drop_table('data_source')
    op.drop_table('cpu')
    op.drop_table('brand')
    # ### end Alembic commands ###
